---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crashguard-secrets
  namespace: crashguard
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: 
  template:
    metadata:
      name: crashguard-secrets
      namespace: crashguard
